package JavaSwing;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Pankaj Yadav
 */
public class AddNewBook extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    String query;

    /**
     * Creates new form AddNewBook
     */
    public AddNewBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        c3 = new javax.swing.JComboBox<>();
        c4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Buku");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kGradientPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 407, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Buku");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 126, -1, -1));

        txt3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kGradientPanel1.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 123, 407, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Penulis");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 167, -1, -1));

        txt4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kGradientPanel1.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 164, 407, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kelompok Jurusan");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 218, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kelompok Semester");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 268, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 323, 250, -1));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 323, 250, -1));

        c3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Jurusan", "Teknik Elektro", "Teknik Informatika", "Agroteknologi", "Fisikia", "Kimia", "Biologi", "Matematika" }));
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 215, 407, -1));

        c4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester" }));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 265, 407, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Tambahkan Buku Baru");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 140, -1));

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Pinjam Buku");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 130, -1));

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Kembalikan Buku");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 140, -1));

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Detail Peminjaman");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 130, -1));

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Detail Buku");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 130, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaSwing/book.png"))); // NOI18N
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 540, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        
    }//GEN-LAST:event_c4ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        if(c3.getSelectedItem()=="Teknik Elektro")
        {
            c4.removeAllItems();
            c4.addItem("Select Semester");c4.addItem("1-TE");c4.addItem("2-TE");c4.addItem("3-TE");
            c4.addItem("4-TE");c4.addItem("5-TE");c4.addItem("6-TE");c4.addItem("7-TE");c4.addItem("8-TE");
            c4.addItem("9-TE");c4.addItem("10-TE");c4.addItem("11-TE");c4.addItem("12-TE");c4.addItem("13-TE");
            c4.addItem("14-TE");
        }
        if(c3.getSelectedItem()=="Teknik Informatika")
        {
            c4.removeAllItems();
            c4.addItem("Select Semester");c4.addItem("1-TI");c4.addItem("2-TI");c4.addItem("3-TI");
            c4.addItem("4-TI");c4.addItem("5-TI");c4.addItem("6-TI");c4.addItem("7-TI");c4.addItem("8-TI");
            c4.addItem("9-TI");c4.addItem("10-TI");c4.addItem("11-TI");c4.addItem("12-TI");c4.addItem("13-TI");
            c4.addItem("14-TI");
        }
        if(c3.getSelectedItem()=="Agroteknologi")
        {
            c4.removeAllItems();
            c4.addItem("Select Semester");c4.addItem("1-Agro");c4.addItem("2-Agro");c4.addItem("3-Agro");
            c4.addItem("4-Agro");c4.addItem("5-Agro");c4.addItem("6-Agro");c4.addItem("7-Agro");c4.addItem("8-Agro");
            c4.addItem("9-Agro");c4.addItem("10-Agro");c4.addItem("11-Agro");c4.addItem("12-Agro");c4.addItem("13-Agro");
            c4.addItem("14-Agro");
        }
        if(c3.getSelectedItem()=="Fisika")
        {
            c4.removeAllItems();
            c4.addItem("Select Semester");c4.addItem("1-Fis");c4.addItem("2-Fis");c4.addItem("3-Fis");
            c4.addItem("4-Fis");c4.addItem("5-Fis");c4.addItem("6-Fis");c4.addItem("7-Fis");c4.addItem("8-Fis");
            c4.addItem("9-Fis");c4.addItem("10-Fis");c4.addItem("11-Fis");c4.addItem("12-Fis");c4.addItem("13-Fis");
            c4.addItem("14-Fis");
        }
        if(c3.getSelectedItem()=="Biologi")
        {
            c4.removeAllItems();
            c4.addItem("Select Semester");c4.addItem("1-Bio");c4.addItem("2-Bio");c4.addItem("3-Bio");
            c4.addItem("4-Bio");c4.addItem("5-Bio");c4.addItem("6-Bio");c4.addItem("7-Bio");c4.addItem("8-Bio");
            c4.addItem("9-Bio");c4.addItem("10-Bio");c4.addItem("11-Bio");c4.addItem("12-Bio");c4.addItem("13-Bio");
            c4.addItem("14-Bio");
        }
        if(c3.getSelectedItem()=="Kimia")
        {
            c4.removeAllItems();
            c4.addItem("Select Semester");c4.addItem("1-Kim");c4.addItem("2-Kim");c4.addItem("3-Kim");
            c4.addItem("4-Kim");c4.addItem("5-Kim");c4.addItem("6-Kim");c4.addItem("7-Kim");c4.addItem("8-Kim");
            c4.addItem("9-Kim");c4.addItem("10-Kim");c4.addItem("11-Kim");c4.addItem("12-Kim");c4.addItem("13-Kim");
            c4.addItem("14-Kim");
        }
        if(c3.getSelectedItem()=="Matematika")
        {
            c4.removeAllItems();
            c4.addItem("Select Semester");c4.addItem("1-MTK");c4.addItem("2-MTK");c4.addItem("3-MTK");
            c4.addItem("4-MTK");c4.addItem("5-MTK");c4.addItem("6-MTK");c4.addItem("7-MTK");c4.addItem("8-MTK");
            c4.addItem("9-MTK");c4.addItem("10-MTK");c4.addItem("11-MTK");c4.addItem("12-MTK");c4.addItem("13-MTK");
            c4.addItem("14-MTK");
        }
    }//GEN-LAST:event_c3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainLayer mn=new MainLayer();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainLayer mn=new MainLayer();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txt2.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Tolong Masukkan ID Buku"); 
        else if(txt3.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Tolong Masukkan Nama Buku"); 
        else if(txt3.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Tolong Masukkan Nama Penulis"); 
        else if(c3.getSelectedItem().equals("Select Jurusan"))
            JOptionPane.showMessageDialog(this,"Tolong Pilih Kelompok Jurusan");
        else if(c4.getSelectedItem().equals("Select Semester"))
            JOptionPane.showMessageDialog(this,"Tolong Pilih Kelompok Semester");    
        else
        {
        try
        {
        connect();
        query="insert into buku values('"+txt2.getText()+"','"+txt3.getText()+"','"+txt4.getText()+"','"+c3.getSelectedItem()+"','"+c4.getSelectedItem()+"','YES');";
        stmt.executeUpdate(query);
        
        disconnect();
        JOptionPane.showMessageDialog(this,"Buku Baru Telah Ditambahkan Ke Perpustakaan");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        c3.setSelectedIndex(0);
        c4.removeAllItems();
        c4.addItem("Select Semester");
        
        }
        catch(SQLException e)
        {
            if(e.getErrorCode()==1062)
                JOptionPane.showMessageDialog(this,"IDBuku adalah sebuah primary key\nmasukan duplikasi tidak diperbolehkan\nID Buku yang seharusnya adalah unique");
            else
                JOptionPane.showMessageDialog(this,"Koneksi Error");
        }
                }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        IssueBook ib=new IssueBook();
        ib.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ReturnBook rb=new ReturnBook();
        rb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        IssuedBooks ibs=new IssuedBooks();
        ibs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        BookDetails bd=new BookDetails();
        bd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddNewBook().setVisible(true);
//            }
//        });
//    }

    public void connect()
    {
        try
        {  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/uinsgdxsaintek-library","root","");  
            stmt=con.createStatement(); 
        }
        catch(Exception e)
        { 
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Koneksi Error");
        }
    }
    public void disconnect()
    {
        try
        {
           con.close(); 
        }
        catch(Exception e)
        {}

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JComboBox<String> c4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    // End of variables declaration//GEN-END:variables
}
