package JavaSwing;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class EditRegis extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    ResultSet rs;
    String query;
    String  checkAvailability,SName,Address,SStream,SClass;
    public EditRegis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        a1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("MENU EDIT DATA MAHASISWA");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIM");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 344, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jurusan");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        c1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Jurusan", "Teknik Elektro", "Teknik Informatika", "Agroteknologi", "Fisikia", "Kimia", "Biologi", "Matematika" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 344, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Semester");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        c2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester" }));
        kGradientPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 344, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        a1.setColumns(20);
        a1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        a1.setRows(5);
        jScrollPane1.setViewportView(a1);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 241, 81));

        jButton1.setBackground(new java.awt.Color(204, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 70, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("=>");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        t3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t3.setEnabled(false);
        kGradientPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 340, -1));

        t4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kGradientPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 340, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 130, -1));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 130, -1));

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 290, -1));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Hapus Data Mahasiswa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NIM");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaSwing/regis.png"))); // NOI18N
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 670, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        if(c1.getSelectedItem()=="Teknik Elektro")
        {
            c2.removeAllItems();
            c2.addItem("Select Semester");c2.addItem("1-TE");c2.addItem("2-TE");c2.addItem("3-TE");
            c2.addItem("4-TE");c2.addItem("5-TE");c2.addItem("6-TE");c2.addItem("7-TE");c2.addItem("8-TE");
            c2.addItem("9-TE");c2.addItem("10-TE");c2.addItem("11-TE");c2.addItem("12-TE");c2.addItem("13-TE");
            c2.addItem("14-TE");
        }
        if(c1.getSelectedItem()=="Teknik Informatika")
        {
            c2.removeAllItems();
            c2.addItem("Select Semester");c2.addItem("1-TI");c2.addItem("2-TI");c2.addItem("3-TI");
            c2.addItem("4-TI");c2.addItem("5-TI");c2.addItem("6-TI");c2.addItem("7-TI");c2.addItem("8-TI");
            c2.addItem("9-TI");c2.addItem("10-TI");c2.addItem("11-TI");c2.addItem("12-TI");c2.addItem("13-TI");
            c2.addItem("14-TI");
        }
        if(c1.getSelectedItem()=="Agroteknologi")
        {
            c2.removeAllItems();
            c2.addItem("Select Semester");c2.addItem("1-Agro");c2.addItem("2-Agro");c2.addItem("3-Agro");
            c2.addItem("4-Agro");c2.addItem("5-Agro");c2.addItem("6-Agro");c2.addItem("7-Agro");c2.addItem("8-Agro");
            c2.addItem("9-Agro");c2.addItem("10-Agro");c2.addItem("11-Agro");c2.addItem("12-Agro");c2.addItem("13-Agro");
            c2.addItem("14-Agro");
        }
        if(c1.getSelectedItem()=="Fisika")
        {
            c2.removeAllItems();
            c2.addItem("Select Semester");c2.addItem("1-Fis");c2.addItem("2-Fis");c2.addItem("3-Fis");
            c2.addItem("4-Fis");c2.addItem("5-Fis");c2.addItem("6-Fis");c2.addItem("7-Fis");c2.addItem("8-Fis");
            c2.addItem("9-Fis");c2.addItem("10-Fis");c2.addItem("11-Fis");c2.addItem("12-Fis");c2.addItem("13-Fis");
            c2.addItem("14-Fis");
        }
        if(c1.getSelectedItem()=="Biologi")
        {
            c2.removeAllItems();
            c2.addItem("Select Semester");c2.addItem("1-Bio");c2.addItem("2-Bio");c2.addItem("3-Bio");
            c2.addItem("4-Bio");c2.addItem("5-Bio");c2.addItem("6-Bio");c2.addItem("7-Bio");c2.addItem("8-Bio");
            c2.addItem("9-Bio");c2.addItem("10-Bio");c2.addItem("11-Bio");c2.addItem("12-Bio");c2.addItem("13-Bio");
            c2.addItem("14-Bio");
        }
        if(c1.getSelectedItem()=="Kimia")
        {
            c2.removeAllItems();
            c2.addItem("Select Semester");c2.addItem("1-Kim");c2.addItem("2-Kim");c2.addItem("3-Kim");
            c2.addItem("4-Kim");c2.addItem("5-Kim");c2.addItem("6-Kim");c2.addItem("7-Kim");c2.addItem("8-Kim");
            c2.addItem("9-Kim");c2.addItem("10-Kim");c2.addItem("11-Kim");c2.addItem("12-Kim");c2.addItem("13-Kim");
            c2.addItem("14-Kim");
        }
        if(c1.getSelectedItem()=="Matematika")
        {
            c2.removeAllItems();
            c2.addItem("Select Semester");c2.addItem("1-MTK");c2.addItem("2-MTK");c2.addItem("3-MTK");
            c2.addItem("4-MTK");c2.addItem("5-MTK");c2.addItem("6-MTK");c2.addItem("7-MTK");c2.addItem("8-MTK");
            c2.addItem("9-MTK");c2.addItem("10-MTK");c2.addItem("11-MTK");c2.addItem("12-MTK");c2.addItem("13-MTK");
            c2.addItem("14-MTK");
        }
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            connect();
            query="select * from mahasiswa where NIM='"+t1.getText()+"';";
            rs=stmt.executeQuery(query); 
            if(rs.next())
            {
                a1.setText(rs.getString("Alamat"));
                t3.setText(rs.getString("NIM"));
                t4.setText(rs.getString("Nama"));
                c1.setSelectedItem(rs.getString("KelompokJurusann"));
                c2.setSelectedItem(rs.getString("KelompokSemesterr"));
            }
            else
                t3.setText("");
                t4.setText("");
                a1.setText("");
                c1.setSelectedItem("Select Jurusan");
                c2.setSelectedItem("Select Semester");
            disconnect();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(t3.getText().equals("")) 
            JOptionPane.showMessageDialog(this,"मान ना मान मैं तेरा मेहमान\nTolong Masukkan NIM Yang Sesuai");
        else if(t4.getText().equals("")) 
            JOptionPane.showMessageDialog(this,"मान ना मान मैं तेरा मेहमान\nKolom Nama Tidak Boleh Kosong!");
        else if(c1.getSelectedItem().equals("Select Jurusan"))
            JOptionPane.showMessageDialog(this,"Tolong Pilih Jurusan!");
        else if(c2.getSelectedItem().equals("Select Semester"))
            JOptionPane.showMessageDialog(this,"Tolong Pilih Semester!");
        else if(a1.getText().equals("")) 
            JOptionPane.showMessageDialog(this,"मान ना मान मैं तेरा मेहमान\nKolom Alamat Tidak Boleh Kosong!");
        else{
        try{
            connect();
            query="select * from mahasiswa where NIM='"+t1.getText()+"';";
            rs=stmt.executeQuery(query);
            if(rs.next())
            {
                query= "UPDATE mahasiswa SET Nama='"+t4.getText()+"', KelompokJurusann='"+c1.getSelectedItem()+"',"
                        + "KelompokSemesterr='"+c2.getSelectedItem()+"',Alamat='"+a1.getText()+"' WHERE NIM='"+t3.getText()+"';";
                stmt.executeUpdate(query);
                
                JOptionPane.showMessageDialog(null, "Edit Data Berhasil...");
                disconnect();
                t4.setText("");
                t3.setText("");
                t1.setText("");
                a1.setText("");
                c1.setSelectedItem("Select Jurusan");
                c2.setSelectedItem("Select Semester");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Gagal Melakukan Perubahan ");
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainLayer mn=new MainLayer();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MainLayer mn=new MainLayer();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(t3.getText().equals("")) 
            JOptionPane.showMessageDialog(this,"मान ना मान मैं तेरा मेहमान\nTolong Masukkan NIM Yang Sesuai");
        else{
                try
                    {
                        connect();
                        query="select * from mahasiswa where NIM='"+t3.getText()+"';";
                        rs=stmt.executeQuery(query);
                        if(rs.next()){
                            query= "DELETE FROM mahasiswa WHERE NIM='"+t3.getText()+"';";
                            stmt.executeUpdate(query);
                            JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data dari NIM nya...");
                            
                            disconnect();
                        }else{
                                JOptionPane.showMessageDialog(this,"Gagal Melakukan Perubahan ");
                                }
                    }catch(SQLException e){
                        if(e.getErrorCode()==1062)
                            JOptionPane.showMessageDialog(this,"Gagal Melakukan Perubahan ");
                    }
                }


    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditRegis().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea a1;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
    public void connect()
    {
        try
        {  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/uinsgdxsaintek-library","root","");  
            stmt=con.createStatement(); 
        }
        catch(Exception e)
        { 
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Koneksi Error");
        }
    }
    public void disconnect()
    {
        try
        {
           con.close(); 
        }
        catch(Exception e)
        {}

    }
}